-- 0008_orders.sql
-- Orders support guest checkout (customer_id null) as well as authenticated
-- customers. Line items snapshot product name/price at order time so historical
-- orders remain accurate even after the admin later edits price or description.

create table public.orders (
  id                uuid primary key default gen_random_uuid(),
  order_number      text not null unique,  -- human-readable, generated by trigger
  customer_id       uuid references public.profiles (id) on delete set null,

  status            public.order_status not null default 'pending',
  channel           public.order_channel not null,

  table_number      text,               -- dine-in only
  delivery_address  jsonb,              -- delivery only: {line1, area, notes, lat, lng}

  contact_name      text not null,
  contact_phone     text not null,
  contact_email     text,

  subtotal          numeric(10, 2) not null check (subtotal >= 0),
  delivery_fee      numeric(10, 2) not null default 0 check (delivery_fee >= 0),
  tax_amount        numeric(10, 2) not null default 0 check (tax_amount >= 0),
  discount_amount   numeric(10, 2) not null default 0 check (discount_amount >= 0),
  total_amount      numeric(10, 2) not null check (total_amount >= 0),

  payment_status    public.payment_status not null default 'unpaid',
  payment_method    text,               -- e.g. 'cash', 'mpesa', 'card'

  notes             text,

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

comment on table public.orders is
  'Totals are always recalculated and verified server-side before insert — never '
  'trusted from client-submitted values.';

create index orders_customer_id_idx on public.orders (customer_id);
create index orders_status_idx on public.orders (status);
create index orders_channel_idx on public.orders (channel);
create index orders_created_at_idx on public.orders (created_at desc);

create table public.order_items (
  id                     uuid primary key default gen_random_uuid(),
  order_id               uuid not null references public.orders (id) on delete cascade,
  product_id             uuid references public.products (id) on delete set null,
  variant_id             uuid references public.product_variants (id) on delete set null,

  -- Snapshots: preserved even if the product/variant is later edited or deleted.
  product_name_snapshot  text not null,
  variant_name_snapshot  text,
  unit_price_snapshot    numeric(10, 2) not null check (unit_price_snapshot >= 0),

  quantity               integer not null check (quantity > 0),
  line_total             numeric(10, 2) not null check (line_total >= 0),

  destination            public.fulfillment_destination not null default 'none',
  special_instructions   text,

  created_at             timestamptz not null default now()
);

create index order_items_order_id_idx on public.order_items (order_id);
create index order_items_product_id_idx on public.order_items (product_id);
create index order_items_destination_idx on public.order_items (destination);

create table public.order_item_addons (
  id                  uuid primary key default gen_random_uuid(),
  order_item_id       uuid not null references public.order_items (id) on delete cascade,
  addon_option_id     uuid references public.addon_options (id) on delete set null,
  addon_name_snapshot text not null,
  price_delta_snapshot numeric(10, 2) not null default 0
);

create index order_item_addons_order_item_id_idx
  on public.order_item_addons (order_item_id);
